export {
  annualRateToDailyRate,
  buildAccumulatedIndexFactor,
  buildTaxBreakdown,
  compoundByAnnualRate,
  compoundByDailyRate,
  compoundChain,
  getIofRateByDays,
  getIrRateByDays,
  type CompoundChainPeriod,
  type TaxBreakdown,
  type TaxedReturn,
} from './core'
export {
  calculateCdiInvestment,
  calculateCdbFromCdiInvestment,
  calculateCraFromCdiInvestment,
  calculateLcaFromCdiInvestment,
  calculateLciFromCdiInvestment,
  calculateSelicInvestment,
  calculateTreasurySelicInvestment,
  calculateVariableCdiSelicInvestment,
  type CdiInvestmentInput,
  type SelicInvestmentInput,
  type VariableCdiSelicInvestmentInput,
  type VariableCdiSelicPeriod,
} from './cdi-selic'
export {
  calculateCdbFromIpcaInvestment,
  calculateCraFromIgpmInvestment,
  calculateCraFromIpcaInvestment,
  calculateCriFromIpcaInvestment,
  calculateIgpmPlusInvestment,
  calculateIpcaPlusInvestment,
  calculateLcaFromIpcaInvestment,
  calculateLciFromIpcaInvestment,
  calculateTreasuryEducationAccumulation,
  calculateTreasuryIncomeAAccumulation,
  calculateTreasuryIpcaInvestment,
  calculateVariableIpcaInvestment,
  type IndexedInvestmentInput,
  type IndexedMtmInput,
  type VariableIndexedInvestmentInput,
} from './ipca'
export {
  calculateFixedRateCdbInvestment,
  calculateFixedRateCraInvestment,
  calculateFixedRateCriInvestment,
  calculateFixedRateEarlyRedemption,
  calculateFixedRateInvestment,
  calculateFixedRateLcaInvestment,
  calculateFixedRateLciInvestment,
  calculateTreasuryFixedRateInvestment,
  type FixedRateInvestmentInput,
} from './fixed-rate'
export {
  calculateTreasuryFixedRateMtm,
  calculateTreasuryIpcaMtm,
  type TreasuryIpcaMtmInput,
  type TreasuryPrefixadoMtmInput,
} from './market'
