/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TiposRouteImport } from './routes/tipos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as PortfolioHoldingsRouteImport } from './routes/portfolio/holdings'
import { Route as PortfolioAporteRouteImport } from './routes/portfolio/aporte'
import { Route as InvestimentosIaEmLoteRouteImport } from './routes/investimentos/ia-em-lote'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as TiposTypeIdPerguntasRouteImport } from './routes/tipos/$typeId/perguntas'
import { Route as PortfolioAporteHistoricoRouteImport } from './routes/portfolio/aporte/historico'
import { Route as InvestimentosIdPontuacaoRouteImport } from './routes/investimentos/$id/pontuacao'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TiposRoute = TiposRouteImport.update({
  id: '/tipos',
  path: '/tipos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const PortfolioHoldingsRoute = PortfolioHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioAporteRoute = PortfolioAporteRouteImport.update({
  id: '/aporte',
  path: '/aporte',
  getParentRoute: () => PortfolioRoute,
} as any)
const InvestimentosIaEmLoteRoute = InvestimentosIaEmLoteRouteImport.update({
  id: '/ia-em-lote',
  path: '/ia-em-lote',
  getParentRoute: () => InvestimentosRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const TiposTypeIdPerguntasRoute = TiposTypeIdPerguntasRouteImport.update({
  id: '/$typeId/perguntas',
  path: '/$typeId/perguntas',
  getParentRoute: () => TiposRoute,
} as any)
const PortfolioAporteHistoricoRoute =
  PortfolioAporteHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => PortfolioAporteRoute,
  } as any)
const InvestimentosIdPontuacaoRoute =
  InvestimentosIdPontuacaoRouteImport.update({
    id: '/$id/pontuacao',
    path: '/$id/pontuacao',
    getParentRoute: () => InvestimentosRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investimentos': typeof InvestimentosRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tipos': typeof TiposRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/settings': typeof AccountSettingsRoute
  '/investimentos/ia-em-lote': typeof InvestimentosIaEmLoteRoute
  '/portfolio/aporte': typeof PortfolioAporteRouteWithChildren
  '/portfolio/holdings': typeof PortfolioHoldingsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/investimentos/$id/pontuacao': typeof InvestimentosIdPontuacaoRoute
  '/portfolio/aporte/historico': typeof PortfolioAporteHistoricoRoute
  '/tipos/$typeId/perguntas': typeof TiposTypeIdPerguntasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investimentos': typeof InvestimentosRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tipos': typeof TiposRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/settings': typeof AccountSettingsRoute
  '/investimentos/ia-em-lote': typeof InvestimentosIaEmLoteRoute
  '/portfolio/aporte': typeof PortfolioAporteRouteWithChildren
  '/portfolio/holdings': typeof PortfolioHoldingsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/investimentos/$id/pontuacao': typeof InvestimentosIdPontuacaoRoute
  '/portfolio/aporte/historico': typeof PortfolioAporteHistoricoRoute
  '/tipos/$typeId/perguntas': typeof TiposTypeIdPerguntasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investimentos': typeof InvestimentosRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tipos': typeof TiposRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/settings': typeof AccountSettingsRoute
  '/investimentos/ia-em-lote': typeof InvestimentosIaEmLoteRoute
  '/portfolio/aporte': typeof PortfolioAporteRouteWithChildren
  '/portfolio/holdings': typeof PortfolioHoldingsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/investimentos/$id/pontuacao': typeof InvestimentosIdPontuacaoRoute
  '/portfolio/aporte/historico': typeof PortfolioAporteHistoricoRoute
  '/tipos/$typeId/perguntas': typeof TiposTypeIdPerguntasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/investimentos'
    | '/login'
    | '/portfolio'
    | '/reset-password'
    | '/tipos'
    | '/verify-email'
    | '/account/profile'
    | '/account/settings'
    | '/investimentos/ia-em-lote'
    | '/portfolio/aporte'
    | '/portfolio/holdings'
    | '/account/'
    | '/admin/'
    | '/api/auth/$'
    | '/investimentos/$id/pontuacao'
    | '/portfolio/aporte/historico'
    | '/tipos/$typeId/perguntas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/investimentos'
    | '/login'
    | '/portfolio'
    | '/reset-password'
    | '/tipos'
    | '/verify-email'
    | '/account/profile'
    | '/account/settings'
    | '/investimentos/ia-em-lote'
    | '/portfolio/aporte'
    | '/portfolio/holdings'
    | '/account'
    | '/admin'
    | '/api/auth/$'
    | '/investimentos/$id/pontuacao'
    | '/portfolio/aporte/historico'
    | '/tipos/$typeId/perguntas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/investimentos'
    | '/login'
    | '/portfolio'
    | '/reset-password'
    | '/tipos'
    | '/verify-email'
    | '/account/profile'
    | '/account/settings'
    | '/investimentos/ia-em-lote'
    | '/portfolio/aporte'
    | '/portfolio/holdings'
    | '/account/'
    | '/admin/'
    | '/api/auth/$'
    | '/investimentos/$id/pontuacao'
    | '/portfolio/aporte/historico'
    | '/tipos/$typeId/perguntas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvestimentosRoute: typeof InvestimentosRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TiposRoute: typeof TiposRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipos': {
      id: '/tipos'
      path: '/tipos'
      fullPath: '/tipos'
      preLoaderRoute: typeof TiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/portfolio/holdings': {
      id: '/portfolio/holdings'
      path: '/holdings'
      fullPath: '/portfolio/holdings'
      preLoaderRoute: typeof PortfolioHoldingsRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/aporte': {
      id: '/portfolio/aporte'
      path: '/aporte'
      fullPath: '/portfolio/aporte'
      preLoaderRoute: typeof PortfolioAporteRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/investimentos/ia-em-lote': {
      id: '/investimentos/ia-em-lote'
      path: '/ia-em-lote'
      fullPath: '/investimentos/ia-em-lote'
      preLoaderRoute: typeof InvestimentosIaEmLoteRouteImport
      parentRoute: typeof InvestimentosRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/tipos/$typeId/perguntas': {
      id: '/tipos/$typeId/perguntas'
      path: '/$typeId/perguntas'
      fullPath: '/tipos/$typeId/perguntas'
      preLoaderRoute: typeof TiposTypeIdPerguntasRouteImport
      parentRoute: typeof TiposRoute
    }
    '/portfolio/aporte/historico': {
      id: '/portfolio/aporte/historico'
      path: '/historico'
      fullPath: '/portfolio/aporte/historico'
      preLoaderRoute: typeof PortfolioAporteHistoricoRouteImport
      parentRoute: typeof PortfolioAporteRoute
    }
    '/investimentos/$id/pontuacao': {
      id: '/investimentos/$id/pontuacao'
      path: '/$id/pontuacao'
      fullPath: '/investimentos/$id/pontuacao'
      preLoaderRoute: typeof InvestimentosIdPontuacaoRouteImport
      parentRoute: typeof InvestimentosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InvestimentosRouteChildren {
  InvestimentosIaEmLoteRoute: typeof InvestimentosIaEmLoteRoute
  InvestimentosIdPontuacaoRoute: typeof InvestimentosIdPontuacaoRoute
}

const InvestimentosRouteChildren: InvestimentosRouteChildren = {
  InvestimentosIaEmLoteRoute: InvestimentosIaEmLoteRoute,
  InvestimentosIdPontuacaoRoute: InvestimentosIdPontuacaoRoute,
}

const InvestimentosRouteWithChildren = InvestimentosRoute._addFileChildren(
  InvestimentosRouteChildren,
)

interface PortfolioAporteRouteChildren {
  PortfolioAporteHistoricoRoute: typeof PortfolioAporteHistoricoRoute
}

const PortfolioAporteRouteChildren: PortfolioAporteRouteChildren = {
  PortfolioAporteHistoricoRoute: PortfolioAporteHistoricoRoute,
}

const PortfolioAporteRouteWithChildren = PortfolioAporteRoute._addFileChildren(
  PortfolioAporteRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioAporteRoute: typeof PortfolioAporteRouteWithChildren
  PortfolioHoldingsRoute: typeof PortfolioHoldingsRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioAporteRoute: PortfolioAporteRouteWithChildren,
  PortfolioHoldingsRoute: PortfolioHoldingsRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface TiposRouteChildren {
  TiposTypeIdPerguntasRoute: typeof TiposTypeIdPerguntasRoute
}

const TiposRouteChildren: TiposRouteChildren = {
  TiposTypeIdPerguntasRoute: TiposTypeIdPerguntasRoute,
}

const TiposRouteWithChildren = TiposRoute._addFileChildren(TiposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvestimentosRoute: InvestimentosRouteWithChildren,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TiposRoute: TiposRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
