/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiposRouteImport } from './routes/tipos'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioHoldingsRouteImport } from './routes/portfolio/holdings'
import { Route as TiposTypeIdPerguntasRouteImport } from './routes/tipos/$typeId/perguntas'
import { Route as InvestimentosIdPontuacaoRouteImport } from './routes/investimentos/$id/pontuacao'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TiposRoute = TiposRouteImport.update({
  id: '/tipos',
  path: '/tipos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioHoldingsRoute = PortfolioHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => PortfolioRoute,
} as any)
const TiposTypeIdPerguntasRoute = TiposTypeIdPerguntasRouteImport.update({
  id: '/$typeId/perguntas',
  path: '/$typeId/perguntas',
  getParentRoute: () => TiposRoute,
} as any)
const InvestimentosIdPontuacaoRoute =
  InvestimentosIdPontuacaoRouteImport.update({
    id: '/$id/pontuacao',
    path: '/$id/pontuacao',
    getParentRoute: () => InvestimentosRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/investimentos': typeof InvestimentosRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/tipos': typeof TiposRouteWithChildren
  '/portfolio/holdings': typeof PortfolioHoldingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/investimentos/$id/pontuacao': typeof InvestimentosIdPontuacaoRoute
  '/tipos/$typeId/perguntas': typeof TiposTypeIdPerguntasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/investimentos': typeof InvestimentosRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/tipos': typeof TiposRouteWithChildren
  '/portfolio/holdings': typeof PortfolioHoldingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/investimentos/$id/pontuacao': typeof InvestimentosIdPontuacaoRoute
  '/tipos/$typeId/perguntas': typeof TiposTypeIdPerguntasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/investimentos': typeof InvestimentosRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/tipos': typeof TiposRouteWithChildren
  '/portfolio/holdings': typeof PortfolioHoldingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/investimentos/$id/pontuacao': typeof InvestimentosIdPontuacaoRoute
  '/tipos/$typeId/perguntas': typeof TiposTypeIdPerguntasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/investimentos'
    | '/login'
    | '/portfolio'
    | '/tipos'
    | '/portfolio/holdings'
    | '/api/auth/$'
    | '/investimentos/$id/pontuacao'
    | '/tipos/$typeId/perguntas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/investimentos'
    | '/login'
    | '/portfolio'
    | '/tipos'
    | '/portfolio/holdings'
    | '/api/auth/$'
    | '/investimentos/$id/pontuacao'
    | '/tipos/$typeId/perguntas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/investimentos'
    | '/login'
    | '/portfolio'
    | '/tipos'
    | '/portfolio/holdings'
    | '/api/auth/$'
    | '/investimentos/$id/pontuacao'
    | '/tipos/$typeId/perguntas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  InvestimentosRoute: typeof InvestimentosRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  TiposRoute: typeof TiposRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tipos': {
      id: '/tipos'
      path: '/tipos'
      fullPath: '/tipos'
      preLoaderRoute: typeof TiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/holdings': {
      id: '/portfolio/holdings'
      path: '/holdings'
      fullPath: '/portfolio/holdings'
      preLoaderRoute: typeof PortfolioHoldingsRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/tipos/$typeId/perguntas': {
      id: '/tipos/$typeId/perguntas'
      path: '/$typeId/perguntas'
      fullPath: '/tipos/$typeId/perguntas'
      preLoaderRoute: typeof TiposTypeIdPerguntasRouteImport
      parentRoute: typeof TiposRoute
    }
    '/investimentos/$id/pontuacao': {
      id: '/investimentos/$id/pontuacao'
      path: '/$id/pontuacao'
      fullPath: '/investimentos/$id/pontuacao'
      preLoaderRoute: typeof InvestimentosIdPontuacaoRouteImport
      parentRoute: typeof InvestimentosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InvestimentosRouteChildren {
  InvestimentosIdPontuacaoRoute: typeof InvestimentosIdPontuacaoRoute
}

const InvestimentosRouteChildren: InvestimentosRouteChildren = {
  InvestimentosIdPontuacaoRoute: InvestimentosIdPontuacaoRoute,
}

const InvestimentosRouteWithChildren = InvestimentosRoute._addFileChildren(
  InvestimentosRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioHoldingsRoute: typeof PortfolioHoldingsRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioHoldingsRoute: PortfolioHoldingsRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface TiposRouteChildren {
  TiposTypeIdPerguntasRoute: typeof TiposTypeIdPerguntasRoute
}

const TiposRouteChildren: TiposRouteChildren = {
  TiposTypeIdPerguntasRoute: TiposTypeIdPerguntasRoute,
}

const TiposRouteWithChildren = TiposRoute._addFileChildren(TiposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  InvestimentosRoute: InvestimentosRouteWithChildren,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  TiposRoute: TiposRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
